
spring:
  application:
    name: management-system-service

  datasource:
    url: jdbc:h2:mem:management_system_db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: auto

  h2:
    console:
      enabled: true
      path: /h2-console
